{{- if and .Values.hubble.export.dynamic.enabled .Values.hubble.export.dynamic.config.createConfigMap }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.hubble.metrics.dynamic.config.configMapName }}
  namespace: {{ include "cilium.namespace" . }}
data:
  flowlogs.yaml: |
    flowLogs:
{{ .Values.hubble.metrics.dynamic.config.content | toYaml | indent 4 }}
{{- end }}
